In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# Test Test Test

In [9]:
test_df = pd.read_csv('daily_aqi_by_county_2020.csv')

In [10]:
test_df

,State Name,county Name,State Code,County Code,Date,AQI,Category,Defining Parameter,Defining Site,Number of Sites Reporting
0,Alabama,Baldwin,1,3,1/1/20,48,Good,PM2.5,01-003-0010,1
1,Alabama,Baldwin,1,3,1/4/20,13,Good,PM2.5,01-003-0010,1
2,Alabama,Baldwin,1,3,1/7/20,14,Good,PM2.5,01-003-0010,1
3,Alabama,Baldwin,1,3,1/10/20,39,Good,PM2.5,01-003-0010,1
4,Alabama,Baldwin,1,3,1/13/20,29,Good,PM2.5,01-003-0010,1
...,...,...,...,...,...,...,...,...,...,...
338190,Wyoming,Weston,56,45,12/27/20,32,Good,Ozone,56-045-0003,2
338191,Wyoming,Weston,56,45,12/28/20,30,Good,Ozone,56-045-0003,2
338192,Wyoming,Weston,56,45,12/29/20,33,Good,Ozone,56-045-0003,2
338193,Wyoming,Weston,56,45,12/30/20,33,Good,Ozone,56-045-0003,2
338194,Wyoming,Weston,56,45,12/31/20,34,Good,Ozone,56-045-0003,2

In [11]:
test_df.head()

,State Name,county Name,State Code,County Code,Date,AQI,Category,Defining Parameter,Defining Site,Number of Sites Reporting
0,Alabama,Baldwin,1,3,1/1/20,48,Good,PM2.5,01-003-0010,1
1,Alabama,Baldwin,1,3,1/4/20,13,Good,PM2.5,01-003-0010,1
2,Alabama,Baldwin,1,3,1/7/20,14,Good,PM2.5,01-003-0010,1
3,Alabama,Baldwin,1,3,1/10/20,39,Good,PM2.5,01-003-0010,1
4,Alabama,Baldwin,1,3,1/13/20,29,Good,PM2.5,01-003-0010,1