In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from numpy import nan as Nan

In [2]:
df_original = pd.read_csv('annual_aqi_by_county_2020.csv')

In [3]:
df= df_original.drop(columns=['Days with AQI', 'Good Days', 'Moderate Days', 'Unhealthy for Sensitive Groups Days','Unhealthy Days'])

In [4]:
df= df.drop(columns=['Very Unhealthy Days','Hazardous Days','Days CO','Days NO2','Days Ozone','Days SO2','Days PM2.5','Days PM10'])

df

pdToList_county = list(df['County'])

pdToList_county

def first_word(pdToList_county):
    my_list = [x.split()[0] for x in pdToList_county]
    return my_list

County = first_word(pdToList_county)

df.insert(2, 'First Word of Each County', County)

df.to_csv('df.csv')


df = pd.read_csv('df_test2.csv')

In [5]:
edu_original = pd.read_csv('Education (1).csv')

In [6]:

neglect2013 = [col for col in edu_original if '2013' in col]
edu = edu_original.drop(columns=neglect2013)

neglect2003 = [col for col in edu_original if '2003' in col]
edu = edu.drop(columns=neglect2003)
edu

neglect1970 = [col for col in edu if '1970' in col]
edu = edu.drop(columns=neglect1970)
edu

neglect1980 = [col for col in edu if '1980' in col]
edu = edu.drop(columns=neglect1980)
edu

neglect1990 = [col for col in edu if '1990' in col]
edu = edu.drop(columns=neglect1990)
edu

neglect2000 = [col for col in edu if '2000' in col]
edu = edu.drop(columns=neglect2000)
edu

edu= edu.drop(columns=['FIPS Code'])
edu= edu.drop(columns=["Less than a high school diploma, 2015-19","High school diploma only, 2015-19","Some college or associate's degree, 2015-19"])
edu= edu.drop(columns=["Bachelor's degree or higher, 2015-19","Percent of adults with less than a high school diploma, 2015-19"])
edu= edu.drop(columns=["Percent of adults completing some college or associate's degree, 2015-19"])


pdToList_area_name = list(edu['Area name'])

pdToList_area_name

def first_word(pdToList_area_name):
    my_list = [x.split()[0] for x in pdToList_area_name]
    return my_list

Area_name = first_word(pdToList_area_name)

edu.insert(2, 'First Word of Each County', Area_name)

edu.to_csv('edu.csv')

edu=pd.read_csv('edu_test.csv')
edu


population_by_county = pd.read_csv('PopulationByCounties.csv')


#edu

In [7]:
#population_by_county

In [8]:
#pd.merge(population_by_county,edu,how="inner",on="Abbreviation")

In [9]:
merged_inner = pd.merge(left=df, right=edu, left_on=['Abbreviation'], right_on=['Abbreviation'])


#merged_= merged_inner.drop(columns="Abbreviation")
merged_= merged_inner.drop(columns="Area name")
merged_= merged_.drop(columns="State_y")
merged_= merged_.drop(columns="First Word of Each County_x")
merged_= merged_.drop(columns="First Word of Each County_y")
merged_=merged_.rename(columns={"State_x": "State"})
merged_.to_csv('merged_show.csv')
#merged_

In [10]:
empl_original = pd.read_csv('Unemployment.csv')

empl=empl_original[~empl_original.Attribute.str.contains("2000")]
empl=empl[~empl.Attribute.str.contains("2001")]
empl=empl[~empl.Attribute.str.contains("2002")]
empl=empl[~empl.Attribute.str.contains("2003")]
empl=empl[~empl.Attribute.str.contains("2004")]
empl=empl[~empl.Attribute.str.contains("2005")]
empl=empl[~empl.Attribute.str.contains("2006")]
empl=empl[~empl.Attribute.str.contains("2007")]
empl=empl[~empl.Attribute.str.contains("2008")]
empl=empl[~empl.Attribute.str.contains("2009")]
empl=empl[~empl.Attribute.str.contains("2010")]
empl=empl[~empl.Attribute.str.contains("2011")]
empl=empl[~empl.Attribute.str.contains("2012")]
empl=empl[~empl.Attribute.str.contains("2013")]
empl=empl[~empl.Attribute.str.contains("2014")]
empl=empl[~empl.Attribute.str.contains("2015")]
empl=empl[~empl.Attribute.str.contains("2016")]
empl=empl[~empl.Attribute.str.contains("2017")]
empl=empl[~empl.Attribute.str.contains("2019")]
empl=empl[~empl.Attribute.str.contains("2018")]
empl=empl[~empl.Attribute.str.contains("Civilian")]
empl=empl[~empl.Attribute.str.contains("rate")]

employed = empl[~empl.Attribute.str.contains("Unemployed")]
employed = employed.rename(columns={"Value": "# Employed"})
employed = employed.drop(columns=['Attribute'])

In [11]:
unemployed = empl[~empl.Attribute.str.contains("Employed")]
unemployed = unemployed.rename(columns={"Value": "# Unemployed"})
unemployed=unemployed.drop(columns=['Attribute'])

In [12]:
Employment_df = pd.merge(left=employed, right=unemployed, left_on=['Area_name'], right_on=['Area_name'])
Employment_df
pdToList_area_name = list(Employment_df['Area_name'])
pdToList_area_name
def first_word(pdToList_area_name):
    my_list = [x.split()[0] for x in pdToList_area_name]
    return my_list

Area_name = first_word(pdToList_area_name)

Employment_df.insert(2, 'First Word of Each County', Area_name)
Employment_df.to_csv('Employment_df.csv')

In [13]:
Employment_numbers=pd.read_csv('Employment_df_test.csv')
#Employment_numbers

In [14]:
merged_2 = pd.merge(left=merged_, right=Employment_numbers, left_on=['Abbreviation'], right_on=['Abbreivation'])
merged_2=merged_2.drop_duplicates(subset=["# Employed","# Unemployed"])
merged_2.to_csv('merged2.csv')

In [15]:
updated_12_02 = pd.read_csv('merged2_cleanedUP.csv')

In [16]:
updated_12_02

,State,County,Abbreviation,Max AQI,90th Percentile AQI,Median AQI,"Percent of adults with a high school diploma only, 2015-19","Percent of adults with a bachelor's degree or higher, 2015-19",# Employed,# Unemployed
0,Alabama,Baldwin,AlabamaBaldwin,74,49,36,27.7,31.9,91338,5425
1,Alabama,Russell,AlabamaRussell,99,56,36,31.4,17.8,22290,1210
2,Alabama,Shelby,AlabamaShelby,71,46,28,19.8,42.9,109646,4402
3,Alabama,Sumter,AlabamaSumter,70,43,29,35.4,21.6,4414,331
4,Alabama,Tuscaloosa,AlabamaTuscaloosa,97,45,31,29.9,30.7,95473,6749
...,...,...,...,...,...,...,...,...,...,...
970,Wyoming,Sublette,WyomingSublette,151,61,44,34.6,22.8,3765,294
971,Wyoming,Sweetwater,WyomingSweetwater,1250,76,46,33.0,22.5,19308,1532
972,Wyoming,Teton,WyomingTeton,161,54,42,14.9,57.0,14292,912
973,Wyoming,Uinta,WyomingUinta,122,51,40,41.5,16.0,8730,582
974,Wyoming,Weston,WyomingWeston,119,49,40,37.4,20.0,3688,148

In [17]:
#population_by_county = pd.read_csv('PopulationByCounties.csv')

In [18]:
#population_by_county

In [19]:
#merged_3 = pd.merge(left=updated_12_02, right=population_by_county, left_on=['Abbreviation'], right_on=['Abbreviation'])

In [20]:
#merged_3

In [21]:
#gross_product=pd.read_csv('Real Gross Domestic Product.csv')

In [22]:
#updated_12_06 = pd.merge(left=updated_12_02, right=gross_product, left_on=['Abbreviation'], right_on=['Area'])

In [23]:
us_county_data=pd.read_csv('us_county.csv')

In [24]:
merged_6 = pd.merge(left=updated_12_02, right=us_county_data, left_on=['Abbreviation'], right_on=['Abbreviation'])
merged_6 = merged_6.drop(columns=['County_y'])
merged_6 = merged_6.drop(columns=['State_y'])
merged_6 = merged_6.rename(columns={"State_x": "State"})
merged_6 = merged_6.rename(columns={"County_x": "County"})
merged_6

,State,County,Abbreviation,Max AQI,90th Percentile AQI,Median AQI,"Percent of adults with a high school diploma only, 2015-19","Percent of adults with a bachelor's degree or higher, 2015-19",# Employed,# Unemployed,Male,Female,Median Age,Population (2014-2020)
0,Alabama,Baldwin,AlabamaBaldwin,74,49,36,27.7,31.9,91338,5425,101188,106919,42.8,208107
1,Alabama,Russell,AlabamaRussell,99,56,36,31.4,17.8,22290,1210,28124,30089,35.9,58213
2,Alabama,Shelby,AlabamaShelby,71,46,28,19.8,42.9,109646,4402,102478,108783,38.9,211261
3,Alabama,Sumter,AlabamaSumter,70,43,29,35.4,21.6,4414,331,6014,6971,35.8,12985
4,Alabama,Tuscaloosa,AlabamaTuscaloosa,97,45,31,29.9,30.7,95473,6749,99539,106674,32.7,206213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,Wyoming,Sublette,WyomingSublette,151,61,44,34.6,22.8,3765,294,5367,4584,39.4,9951
984,Wyoming,Sweetwater,WyomingSweetwater,1250,76,46,33.0,22.5,19308,1532,22882,21235,34.6,44117
985,Wyoming,Teton,WyomingTeton,161,54,42,14.9,57.0,14292,912,11911,11148,39.3,23059
986,Wyoming,Uinta,WyomingUinta,122,51,40,41.5,16.0,8730,582,10505,10104,35.5,20609
987,Wyoming,Weston,WyomingWeston,119,49,40,37.4,20.0,3688,148,3768,3332,42.9,7100

In [25]:
Election_Data = pd.read_csv('Election_Data')

FileNotFoundError: [Errno 2] No such file or directory: 'Election_Data'